# Read the Docs configuration (see https://docs.readthedocs.io/en/stable/config-file/v2.html)

# The 'make meta' command makes recipe/meta.json available to doc-build logic.

version: 2
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    pre_build:
      - make meta
conda:
  environment: docs/environment.yml
sphinx:
  builder: html
  configuration: docs/conf.py
